ALPSCore/ALPSCore

- common/cmake/ALPSEnableTests.cmake
we noticed tests failing because the binary was not found.
> fix tests running with mvapich2.

- common/cmake/ALPSEnableTests.cmake
not the CMAKE_SOURCE_DIR (otherwise failure if module is compiled separately)
> Tests : make gtest path relative to the parent of the PROJECT_SOURCE_DIR

- tutorials/mc/ising_mc/main.cpp
Read-out of `timelimit` and `outputfile` parameters caused `type_mismatch` exceptions to be thrown. With this patch, the Ising tutorial compiles and runs as advertised in the [Wiki](https://github.com/ALPSCore/ALPSCore/wiki/Installation#build-your-project-with-alpscore).
> Fixed type mismatches in Ising example

- mc/include/alps/mc/mpiadapter.hpp
- mc/test/CMakeLists.txt
- mc/test/reduce_unavailable_results.cpp
To ensure backward compatibility, we simply ignore an observable which was not measured on any process.
> Fixed possible MPI deadlock in mcmpiadapter

- utilities/test/test_utils.hpp
Clang 3.8 found that the function call was ambiguous.
> Fixed compilation error (clang 3.8)

- gf/include/alps/gf/mesh.hpp
- gf/include/alps/gf/piecewise_polynomial.hpp
- gf/test/CMakeLists.txt
- gf/test/mesh_test.cpp
- gf/test/mesh_test_mpi.cpp
- gf/test/piecewise_polynomial_test.cpp
The essential change from the previous pull request is that I have removed "scalar_type" dataset in numerical_mesh. This pull request includes two commits. The timestamp of the elder one seems bit strange because I merged several comments into a single one using "rebase -i". It may throw in the constructor of pieacewise_polynomial (see the comment there).
> Numerical basis

- utilities/src/signal.cpp
This removes the handlers for SIGSTOP and SIGKILL, which cannot be caught anyway.
Since valgrind complains when these handlers are present, we might as well remove them.
> Remove signal handlers for SIGSTOP and SIGKILL

- accumulators/include/alps/accumulators/feature/binning_analysis.hpp
- accumulators/include/alps/accumulators/feature/max_num_binning.hpp
To avoid name look-up errors. Even with this fix, ALPSCore does not compile with intel C++ compiler 12.0 due to an internal error.
> Workaround for a bug in intel compiler 12.0

- gf/include/alps/gf/mesh.hpp
- gf/include/alps/gf/piecewise_polynomial.hpp
- gf/test/piecewise_polynomial_test.cpp
Fixed minor bugs. One of them originates from the boost::multi_array's design that we need to resize an object before copying another object into.
> Fixed bugs in numerical_mesh & piecewise_polynomial

- utilities/include/alps/utilities/mpi.hpp
This is a version of MPI_INIT with NULL as parameters (MPI standard 2). It allows easier initialization of MPI e.g. for testing when no default environment arguments are available.
> version of MPI_INIT with NULL as parameters (MPI standard 2)

- params/include/alps/params/convenience_params.hpp
If my understanding is correct, this function should be inlined.
> Made define_convenience_parameters an inline function

- accumulators/test/custom_type.cpp
- accumulators/test/save_load2.cpp
- gf/test/four_index_gf_test.cpp
- gf/test/itime_gf_test.cpp
- gf/test/one_index_gf_test.cpp
- gf/test/seven_index_gf_test.cpp
- gf/test/three_index_gf_test.cpp
- gf/test/two_index_gf_test.cpp
- mc/src/stop_callback.cpp
- mc/test/timer.cpp
- mc/test/timer_in_sim.cpp
Some GF and accumulator tests request the same HDF5 filename,
which is a problem when running the tests in parallel using
`ctest -jXX`.  This assigns a unique filename to all files in
the test.
Also, it tightens some of the timeouts in the MC class.
>  Fixed crashes when running tests in parallel

- params/include/alps/params.hpp
- params/include/alps/params/option_description_type.hpp
- params/include/alps/params/option_type.hpp
- params/include/alps/params/param_types.hpp
- params/include/alps/params/params_impl.hpp
- params/test/CMakeLists.txt
- params/test/apply.cpp
* Added two free functions, `apply()` and `foreach()`.
```c++
/// Pick parameter by name and apply a generic functor f to it.
template <typename F> void apply(const params& opts, const std::string& optname, F const& f);
/// Apply a generic functor f to each defined parameter
template <typename F> void foreach(const params& opts, F const& f);
```
For any allowed parameter type `T`, `f` must be callable as
`f(const std::string& name, boost::optional<T> const& val, boost::optional<T> const& defval, const std::string& descr)`
* Added new method option_description_type::is_trigger().
* Added a unit-test for the new functions.
This interface does not depend on Boost.Program_options, it only requires `boost::optional`, which is in the header-only part. Implementation involves some visitation …
> [params] Fix issue #359

- params/include/alps/params/params_impl.hpp
`params_apply_visitor` should contain specialization of the call operator for `detail::trigger_tag`. Otherwise, user-provided functor `f` will be instantiated for this type (implementation detail leak).
> [params] Correction to 92e92ea2b9a6807487d014c6f2bd107d49da50c6

- params/include/alps/params.hpp
The CT-HYB code still uses "bool defined()", which should be "const".
> Some function marked as const

- hdf5/include/alps/hdf5/archive.hpp
> Disable assignment of hdf5::archive objects

- hdf5/include/alps/hdf5/archive.hpp
- hdf5/test/CMakeLists.txt
- hdf5/test/hdf5_native_type.cpp
> Meta-predicate for "native types" in alps::hdf5

- params/include/alps/params/mpi_variant.hpp
This debug code requires inclusion of iostream. 
This would introduce an unnecessary dependency on iostream.
With this fix, the CT-HYB code now runs correctly with deboost-version of ALPSCore.
> Small bug fix

- alea/include/alps/alea/autocorr.hpp
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/bundle.hpp
- alea/include/alps/alea/complex_op.hpp
- alea/include/alps/alea/computed.hpp
- alea/include/alps/alea/convert.hpp
- alea/include/alps/alea/core.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/hdf5.hpp
- alea/include/alps/alea/internal/util.hpp
- alea/include/alps/alea/mean.hpp
- alea/include/alps/alea/transform.hpp
- alea/include/alps/alea/variance.hpp
- alea/src/autocorr.cpp
- alea/src/batch.cpp
- alea/src/covariance.cpp
- alea/src/mean.cpp
- alea/src/variance.cpp
- alea/test/twogauss.cpp
Now we have basically all the features of the old code in place.
This fixes a couple of bugs:
- no possiblity for serialization of a result
- discarded left-over result in `var_acc` etc.
- wrong variances, covariances in `batch_acc`
>  ALEA: fixed some bugs and added serialization

- common/doc/Doxyfile.in
Removes these warnings:
warning: Tag `CLANG_ASSISTED_PARSING' at line 1060 of file ...
warning: Tag `CLANG_OPTIONS' at line 1068 of file ...
> Quiet doxygen warnings:

- utilities/include/alps/testing/near.hpp
Hi, I got the following compilation error with Intel C++ 17.0.4.196.
There seems to be a bug in the compiler.
I've written a quick workaround. 
Could you review it?
```
In file included from /home/i0412/i041200/git/ALPSCore/alea/test/transform.cpp(9):
/home/i0412/i041200/git/ALPSCore/utilities/include/alps/testing/near.hpp(27): error #501: argument of type "int" is incompatible with template parameter of type "std::enable_if<alps::testing::is_scalar<T>::value, void>::type *"
typename std::enable_if<is_scalar<T>::value>::type * = 0>
^
compilation aborted for /home/i0412/i041200/git/ALPSCore/alea/test/transform.cpp (code 2)
```
> Workaround for Intel C++ 2017

- alea/include/alps/alea/autocorr.hpp
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/hdf5.hpp
- alea/include/alps/alea/mean.hpp
- alea/include/alps/alea/result.hpp
- alea/include/alps/alea/variance.hpp
- alea/src/autocorr.cpp
- alea/src/batch.cpp
- alea/src/covariance.cpp
- alea/src/mean.cpp
- alea/src/result.cpp
- alea/src/variance.cpp
- alea/test/twogauss.cpp
@katherlee @krivenko : this directly affects you
Note that this is compatibility break -- you will have to replace:
alps::alea::mean_result<T> res;
alps::alea::hdf_serializer ser;
// res.serialize(ser);  
alps::alea::serialize(ser, res);
Fixes: #437
Fixes: #438
> [alea] Serialization bug fixes

- gf/include/alps/gf/gf_base.hpp
- utilities/include/alps/numeric/tensors/data_storage.hpp
- utilities/include/alps/numeric/tensors/data_view.hpp
- utilities/include/alps/numeric/tensors/tensor_base.hpp
`const` element access should probably return by `const ref` instead of by value. This is how it is done for both `std::vector` and `boost::multiarray`. I think it is more efficient as well as more flexible since it leaves it up to the consumer how they want to take the value.
> return by const ref instead of value

- params/test/params_test_support.hpp
...by using C++11 lambda rather than std::const_mem_fun_ref_t() in a
param test.
This should fix #443.
> Fix possible ambiguity when taking an address of a function

- common/cmake/ALPSCommonModuleDefinitions.cmake
This is a quick fix to allow installing ALPSCore into its own build directory.
This should address #427.
@ryanlevy Does it fix your problem?
> Allow installing ALPSCore into its own build directory

- CMakeLists.txt
- common/cmake/ALPSCommonModuleDefinitions.cmake
- common/cmake/ALPSCoreConfig.cmake.in
- utilities/include/config.hpp.in
This is to partially address #212 (in particular, https://github.com/ALPSCore/ALPSCore/issues/212#issuecomment-364699130)
1. To exclude a component (and its testsuite) from being built, add
it's name to CMake list `ALPS_MODULES_DISABLE` ::
```sh
cmake .. -DALPS_MODULES_DISABLE=accumulators\;mc
```
2. If some component depends on a disabled component, the dependent component refuses to build.
One needs to disable all dependent components explicitly.
3. The client code may inspect CMake list `ALPSCore_COMPONENTS` after
`find_package(ALPSCore)` to determine if a component is available.
4. The cleint C++ code also has preprocessor symbols `ALPS_HAVE_ALPS_*` defined,
e.g. `ALPS_HAVE_ALPS_GF` or `ALPS_HAVE_ALPS_ACCUMULATORS`, if the corresponding
component is built.
> Introduced selective builds of ALPSCore components

- alea/include/alps/alea/autocorr.hpp
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/core.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/mean.hpp
- alea/include/alps/alea/plugin/stream_serializer.hpp
- alea/include/alps/alea/variance.hpp
- alea/src/autocorr.cpp
- alea/src/batch.cpp
- alea/src/covariance.cpp
- alea/src/mean.cpp
- alea/src/variance.cpp
- alea/test/CMakeLists.txt
- alea/test/stream_serializer.cpp
This plugin should allow for Boost/HPX serialization of `*_result<T>` types.
To enable the plugin for all supported ALEA result types in an HPX application one must include `alps/alea/plugin/stream_serializer.hpp` as follows,
```c++
#include <hpx/runtime/serialization/serialize.hpp>
#include <hpx/runtime/serialization/complex.hpp>
#include <alps/alea/plugin/stream_serializer.hpp>
namespace alps { namespace alea {
HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE((template <typename T>), (mean_result<T>));
HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE((template <typename T>), (var_result<T>));
HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE((template <typename T>), (cov_result<T>));
HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE((template <typename T>), (autocorr_result<T>));
HPX_SERIALIZATION_SPLIT_FREE_TEMPLATE((template …
```
> ALEA: stream_serializer, a result serialization plugin

- alea/include/alps/alea/autocorr.hpp
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/computed.hpp
- alea/include/alps/alea/core.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/mean.hpp
- alea/include/alps/alea/variance.hpp
This adds support for accumulating `std::array`.
It also introduces `is_alea_acc` metafunction and makes insertion operators for non `computed` types into free functions defined in `computed.hpp` where the adapters are defined. I think this makes sense because it removes the 5x duplication of these functions in the definition of every accumulator, shortens the actual accumulator interfaces and doesn't special case any types. The user can add support for accumulating custom types by just following how it is done for `std` types in `computed.hpp`. The only downside I can think of is that now these functions are not explicitly instantiated with the accumulators. However since they are basically one-liners this is probably not too big of a deal.
This is done on top of #446. I will retarget to …
> RFC: [alea] add support for accumulating std::array

- alea/src/propagation.cpp
- alea/test/transform.cpp
This fixes `jackknife()` and extends `transform` unit test to ensure the bug is gone.
The issue was in overflowing subtraction of unsigned arrays.
> [ALEA] Fix jackknife()

- accumulators/include/alps/accumulators/accumulator.hpp
- accumulators/test/CMakeLists.txt
- accumulators/test/mpi_merge.cpp
- accumulators/test/repeated_merge.cpp
- mc/include/alps/mc/mpiadapter.hpp
This is to fix issue #295: duplication on measurements by repeated collective_merge.
Autocorrelation values after repeated merge are not quite correct.
> Resetting slave accumulators

- alea/include/alps/alea/autocorr.hpp
Returns true if a non-vanishing estimate for tau can be calculated.
> [ALEA] Add new method, autocorr_result::tau_available()

- alea/include/alps/alea/complex_op.hpp
Closes #486. Replaces static_cast to function pointer with lambda.
> [alea] fix gcc-7.1 compilation issue

- utilities/include/alps/numeric/inf.hpp
- utilities/include/alps/numeric/real.hpp
I encountered this bug when comping ALPSCore with clang and gcc in C++14 mode.
> Fixed compilation error with C++14

- gf/include/alps/gf/mesh.hpp
- gf/include/alps/gf/piecewise_polynomial.hpp
Hiroshi (@shinaoka), could you please look at it? 
Especially this: 
https://github.com/ALPSCore/ALPSCore/blob/gf-poly-mesh-warnings-20180322/gf/include/alps/gf/piecewise_polynomial.hpp#L169-L173
```c++
valid_ = valid_ && (section_edges_.size() == std::size_t(n_sections_) + 1);
assert(valid_);
valid_ = valid_ && (coeff_.shape()[0] == std::size_t(n_sections_));
assert(valid_);
valid_ = valid_ && (coeff_.shape()[1] == std::size_t(k_+1));
```
It's assumed here that `n_sections_>=0` and `k_+1 >= 0`.
> Fixed signed<>unsigned warnings in GF piecewise-polynomial code

- .travis.yml
- params/src/dict_value.cpp
We build ALPSCore with C++14 in Travis CI.
As expected, builds with C++14 fail due to the bug in Boost 1.58.
> C++14 in Travis CI

- .travis.yml
- common/cmake/ALPSEnableEigen.cmake
Multiple builds in Travis CI sometimes fail due to connection time out (apt & Eigen3).
Here is some workaround for this issue.
> Build failure in Travis CI due to connection time out

- .gitignore
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/result.hpp
- alea/include/alps/alea/variance.hpp
- alea/src/covariance.cpp
- alea/src/result.cpp
- alea/src/variance.cpp
- alea/test/CMakeLists.txt
- alea/test/result.cpp
Also, adds some tests to the generic (variant-based) result class to match that.
Closes: #484
> [alea] Make `count()` consistent over accumulators.

- accumulators/include/alps/accumulators/accumulator.hpp
- accumulators/src/accumulator_wrapper.cpp
- accumulators/test/repeated_merge.cpp
This restores changes by commit
9bd2ff220fe3540e3bc56c2c2c60fe5e41707bc0 ("Reset accumulators on
slaves after merging") which were apparently lost by merge commit
97d4b696ca4ec0ace8090fbf7aa4b7f9837ca0d1.
This should close #508.
> Reset accumulators on slaves after MPI merge

- params/include/alps/params.hpp
- params/src/params.cpp
- params/test/params.cpp
If a parameter object is read from INI or constructed from
(`argc`,`argv`), it gets `--help` option automatically defined.
Calling `params::description(const string&)`  method also defines
`--help` if not already defined.
Default ctor does not define `--help`: empty parameter object is
indeed empty.
Side effect: if for some obscure reason one does not want to have
`--help` defined as a boolean option, there is no way to not have
it. One can always reassign a different type value to `p["help"]` or
erase it, but this will not change the auto-generated help message.
This should close #496.
> Make params help available without setting description

- accumulators/test/mean_err_count.cpp
This disables a buggy test  under OSX & Intel. It fixes #518
> apple intel fix to disable a failing test

- .travis.yml
- common/cmake/ALPSEnableEigen.cmake
The user can set `-DALPS_EIGEN_DOWNLOAD_METHODS` to a list of download methods to try, in the given order. Available methods are `cmake` (using CMake built-in `file`), `wget` (using `wget` utility, if available) and `curl` (using `curl` utility, if available). The default is `cmake;wget;curl`.
This should close #451.
> Try to download Eigen3 using various methods

- common/cmake/ALPSCompilerVersionCheck.cmake
- common/cmake/ALPSCoreConfig.cmake.in
Introduced support for C++17 (when using CMake 3.8+); verify if client should use newer CMake for their project. 
This should close #500.
> Support for C++17

- mc/include/alps/mc/mpiadapter.hpp
RNG seeds of MC chains depend linearly on the chain MPI rank; the
coefficients of the linear dependence can now be set by the caller.
@shinaoka Could you please also have a brief look if you have time?
This should close #307.
> User-settable linear function for RNG seeds in parallel MC

- accumulators/include/alps/accumulators/accumulator.hpp
- accumulators/include/alps/accumulators/feature/weight_holder.hpp
- accumulators/include/alps/accumulators/namedaccumulators.hpp
- accumulators/include/alps/accumulators/wrapper_set.hpp
- accumulators/include/alps/accumulators_.hpp
- accumulators/src/accumulator_wrapper.cpp
- accumulators/src/accumulators.cpp
- accumulators/src/result_wrapper.cpp
- accumulators/src/wrapper_set.cpp
- accumulators/src/wrapper_set_hdf5.cpp
- accumulators/test/binop_mixed.cpp
- accumulators/test/get_results.cpp
- accumulators/test/mpi_merge.cpp
- accumulators/test/mpi_merge_uneven.cpp
- accumulators/test/single_accumulator.cpp
- accumulators/test/zero_vector_mpi.cpp
- utilities/include/alps/utilities/mpi.hpp
- utilities/test/unique_file.cpp
This is a modernization effort inspired by one of Sergei's commits: replacing boost::shared_ptr by std::shared_ptr.
> removing boost::shared_ptr and replacing it with std::shared_ptr

- alea/src/propagation.cpp
This fixes a bug in the jacobian routine that appears for `in_size != out_size`. This is necessary for InchwormHPX and also fairly fundamental so a quick merge would be appreciated.
> [alea] fix size of jacobian matrix

- alea/include/alps/alea/autocorr.hpp
- alea/include/alps/alea/batch.hpp
- alea/include/alps/alea/bundle.hpp
- alea/include/alps/alea/core.hpp
- alea/include/alps/alea/covariance.hpp
- alea/include/alps/alea/hdf5.hpp
- alea/include/alps/alea/internal/galois.hpp
- alea/include/alps/alea/mean.hpp
- alea/include/alps/alea/mpi.hpp
- alea/include/alps/alea/plugin/stream_serializer.hpp
- alea/include/alps/alea/result.hpp
- alea/include/alps/alea/serialize.hpp
- alea/include/alps/alea/util/serializer.hpp
- alea/include/alps/alea/variance.hpp
- alea/src/autocorr.cpp
- alea/src/batch.cpp
- alea/src/covariance.cpp
- alea/src/mean.cpp
- alea/src/result.cpp
- alea/src/variance.cpp
- alea/test/stream_serializer.cpp
On 32-bit system, a 32-bit size_t should be used for indexing into objects, however, we want to use 64-bit counters, because it is very conceivable that more than 1e32 measurements are accumulated in a single run.
Changes `serializer` and `reducer` interfaces accordingly.
@wistaria: since you are the one with a 32-bit system, can you please see if this compiles and all the tests pass?
Fixes: #581
> [alea] Change sizes to `size_t`, counts to `uint64_t`.

- common/build/build_prereq.travis.sh
[This Travis CI workaround for MacOS](https://github.com/travis-ci/travis-ci/issues/8826#issuecomment-350103392) is [not needed anymore](https://changelog.travis-ci.com/oclint-is-removed-from-mac-builds-79270) and is causing problems.
This should close #592.
> Fixed Travis CI MacOS build

- common/cmake/ALPSEnableTests.cmake
- utilities/test/CMakeLists.txt
- utilities/test/compilation_failure_test.cpp
The idea that CMake tries to build the test code at `make test` (aka `ctest`) time, and expects it to fail. If the code does not fail, the correctly written test is expected to produce an explicit failure upon running (to be recorded in GTest XML output). The fragment of the code that produces the compilation failure should be protected by
```c++
#ifdef ALPS_TEST_EXPECT_COMPILE_FAILURE
// ... compilation failure here ...
#endif 
```
guards, so that "normal" compilation and running of the code records a successful test passing.
> CMake machinery to do postive compilation failure testing

- params/CMakeLists.txt
- params/include/alps/dictionary.hpp
- params/include/alps/params.hpp
- params/include/alps/params/dict_types.hpp
- params/include/alps/params/dict_value.hpp
- params/src/dict_value.cpp
- params/src/dictionary.cpp
- params/src/params.cpp
- params/test/CMakeLists.txt
This PR conditionally decouples `alps::params` from `alps::hdf5`. Specifically, if ALPSCore is built with
`-DALPS_MODULES_DISABLE=hdf5`, the `params` module will be built without archive support. This is useful if all I need from ALPSCore is its `utilities` and `params` modules.
The disadvantage is that the version of ALPSCore build like this is not compatible with the "regular" ALPSCore (e.g., it has different definition of the `alps::params` class).
This PR partially addresses issue #572.
> Ability to decouple alps::params from alps::hdf5

- alea/include/alps/alea/core.hpp
- alea/include/alps/alea/hdf5.hpp
- alea/include/alps/alea/plugin/stream_serializer.hpp
- alea/include/alps/alea/serialize.hpp
- alea/include/alps/alea/util/serializer.hpp
- alea/src/covariance.cpp
- alea/src/variance.cpp
- alea/test/stream_serializer.cpp
- utilities/include/alps/common/serialize.hpp
- utilities/include/alps/common/view.hpp
- utilities/include/alps/serialization/core.hpp
- utilities/include/alps/serialization/eigen.hpp
- utilities/include/alps/serialization/util.hpp
This adds the `alps::serialization` namespace.  The ALEA serialization and deserialization infrastructure is moved from `alps::alea` to this namespace, and ALEA imports those back into the `alps::alea` namespace for backwards compatibility.
The tests for serializer remain in the `alea` package for now, since its the only user.
This is step 1 in decoupling parameters from HDF5.
> Elevate ALEA (`de`)`serializer` interface to common.

- utilities/include/alps/numeric/tensors/data_storage.hpp
- utilities/test/tensor_test.cpp
Current move assignment for `tensor` doesn't work as intended. For example, the following
```cpp
using alps::numerics;
tensor<double, 2> a(10, 10);
tensor<double, 2> b;
b = std::move(a);
```
actually copies data from `a` to `b`, instead of moving and invalidating `a`.
Here's a fix for `data_storage` that fixes the move of the storage. After the move, `a` will no longer hold data, and the data is transferred to `b`. However, it will leave the size information in `a` unchanged. This essentially left `a` to an invalid state.
Fixing this would require explicit treatments for different storage types. I would suggest that since the move semantics isn't frequently used we could keep it like this for now.
> Fix move semantics of tensor
