common/misc/alpscore.lmod.in

Now consistent with [tutorial](https://github.com/ALPSCore/ALPSCore/wiki/Tutorial%3A-link).

Update lmod module file to proper structure

---

gf/include/alps/gf/mesh.hpp
gf/test/mesh_test.cpp
gf/test/mesh_test_mpi.cpp

real frequency mesh + bosonic matsubara mesh parameter

real frequency mesh

---

gf/include/alps/gf/gf.hpp
gf/include/alps/gf/mesh.hpp
gf/src/mesh.cpp
gf/test/mesh_test.cpp
gf/test/mesh_test_mpi.cpp
gf/test/one_index_gf_test.cpp

Implemented Legendre representation of gf

Implemented Legendre basis

---

gf/include/alps/gf/gf.hpp
gf/include/alps/gf/mesh.hpp
gf/test/four_index_gf_test.cpp
gf/test/four_index_gf_test.hpp
gf/test/mesh_test.cpp
gf/test/one_index_gf_test.cpp
gf/test/one_index_gf_test.hpp
gf/test/three_index_gf_test.cpp
gf/test/two_index_gf_test.cpp

Could you review the changes?
I have also introduced empty-gf checking.
It throws when an empty gf is accessed.
The overhead should be small.

GFs and meshes are now default-constructive.

---

gf/include/alps/gf/mesh.hpp
gf/include/alps/gf/piecewise_polynomial.hpp
gf/test/mesh_test.cpp
gf/test/mesh_test_mpi.cpp
gf/test/piecewise_polynomial_test.cpp

I've changed the design of numerical mesh. This is for better compatibility with Python interfaces.

Removed template parameter "k" (order of polynomials) from

---

gf/include/alps/gf/gf.hpp
gf/test/CMakeLists.txt
gf/test/seven_index_gf_test.cpp

This is Hiroshi's seven index gf done by copy/paste

seven index gf

---

gf/include/alps/gf/mesh.hpp

I forgot to remove test code which is not never used.
There will be no side effects.

Removed unused code

---

gf/include/alps/gf/gf.hpp

Never call `save()` and `load()` methods of meshes explicitly.

[hdf5/gf] More careful solution of #337

---

accumulators/include/alps/accumulators/feature/binning_analysis.hpp

This explains some of the magic numbers and other stuff in the code
at I was working my way through it.

Adding documentation to binning analysis.

---

accumulators/CMakeLists.txt
hdf5/CMakeLists.txt
mc/CMakeLists.txt
mc/include/alps/mc/check_schedule.hpp
mc/include/alps/mc/stop_callback.hpp
mc/src/stop_callback.cpp
mc/test/check_schedule.cpp
utilities/CMakeLists.txt

Emanuel (@egull). could you please try and see if it runs ok for you?

Removed dependencies on boost::chrono

---

common/cmake/ALPSEnableMPI.cmake

`list(APPEND ...)` is wrong here, since it inserts a semicolon.
Fixes #396.

Correct handling of CXX_FLAGS

---

tutorials/params/cmd_params/main.cpp
tutorials/params/ini_params/main.cpp

Comment param tutorials for params::has_missing()

---

params/include/alps/params/dict_value_impl.hpp
params/src/dict_value.cpp
params/src/params.cpp

Quick fix for issue #402.
(Needs refactoring but should work.)

Quick fix for issue #402: remove vector streaming op from std::

---

alea/include/alps/alea/convert.hpp
alea/include/alps/alea/covariance.hpp
alea/include/alps/alea/hdf5.hpp
alea/include/alps/alea/transform.hpp
alea/include/alps/alea/variance.hpp
alea/src/autocorr.cpp
alea/src/batch.cpp
alea/src/covariance.cpp
alea/src/variance.cpp
alea/test/dataset.hpp
alea/test/twogauss.cpp

Also:
- adds test case.
- removes some debug output left over in HDF5
Fixes #429

[alea] Fixed weighted averages.

---

alea/include/alps/alea/hdf5.hpp
alea/include/alps/alea/mpi.hpp

I encountered some linking errors when using ALEA. Here are some quick fixes for them.

Fixed linking errors.

---

gf/include/alps/gf/gf_base.hpp
utilities/include/alps/numeric/tensors/tensor_base.hpp

I'll be pushing everything we need for InchwormHPX to this branch/PR.

New GF fixes needed for inchworm code

---

alea/include/alps/alea/transform.hpp
gf/include/alps/gf/gf_base.hpp
gf/include/alps/gf/tail_base.hpp
params/test/params_test_support.hpp
utilities/include/alps/numeric/tensors/tensor_base.hpp
utilities/include/alps/type_traits/index_sequence.hpp
utilities/include/alps/type_traits/tuple_traits.hpp

Compiler issues

---

alea/include/alps/alea/result.hpp

[ALEA] Quick fix of `serialize` interface for `result`.

---

.travis.yml
accumulators/include/alps/accumulators/feature.hpp
accumulators/include/alps/accumulators/mpi.hpp
accumulators/src/feature/binning_analysis.cpp
accumulators/src/feature/error.cpp
accumulators/src/feature/max_num_binning.cpp
accumulators/src/feature/mean.cpp
accumulators/src/mpi.cpp

This should fix #472; also i added no-MPI testing to Travis-CI file.

Fix no-MPI build, add no-MPI Travis-CI testing

---

alea/test/CMakeLists.txt

Just don't forget to switch it back...

[ALEA] Disable stream_serializer test until #462 is fixed

---

alea/include/alps/alea/core.hpp

adds `std::initializer_list` constructor to column

[alea] add std::initializer_list constructor to column

---

alea/include/alps/alea/batch.hpp
alea/include/alps/alea/complex_op.hpp
alea/include/alps/alea/covariance.hpp
alea/include/alps/alea/mean.hpp
alea/include/alps/alea/plugin/stream_serializer.hpp
alea/include/alps/alea/variance.hpp
alea/src/covariance.cpp
alea/src/mean.cpp
alea/src/variance.cpp
alea/test/CMakeLists.txt
alea/test/empty.cpp
alea/test/stream_serializer.cpp

[alea] Handle the case of zero/one measurements reponsibly.

---

gf/test/four_index_gf_test_mismatched-tail_mpi.cpp
gf/test/four_index_gf_test_mpi.cpp
gf/test/gf_new_tail_test.cpp
gf/test/gf_new_tail_test_mpi.cpp
gf/test/gf_new_test.cpp
gf/test/mesh_test.cpp
gf/test/multiarray_bcast_mpi.cpp
hdf5/test/hdf5_tensor.cpp
mc/test/sum_mpi.cpp
utilities/include/alps/numeric/tensors/tensor_base.hpp
utilities/test/tensor_test.cpp
utilities/test/vector_functions.cpp

Removed some more warnings

---

params/src/params.cpp
utilities/CMakeLists.txt
utilities/include/alps/utilities/temporary_filename.hpp
utilities/src/temporary_filename.cpp
utilities/test/temporary_filename.cpp

@shinaoka @egull Hotfix for the problem with a temporary file in params

Hotfix for an error creating a temp file in params

---

alea/include/alps/alea/covariance.hpp
alea/include/alps/alea/variance.hpp

Fixes: #484 (hopefully this time)

[alea] Fix inconsistency of count2() type.

---

.travis.yml

...as suggested by Markus (@mwallerb), see issue #511.

Run MPI tests in parallel on Travis

---

gf/include/alps/gf/tail_base.hpp
utilities/include/alps/numeric/tensors/data_storage.hpp
utilities/include/alps/numeric/tensors/data_view.hpp
utilities/include/alps/numeric/tensors/tensor_base.hpp
utilities/include/alps/numeric/tensors/view.hpp
utilities/test/tensor_test.cpp

1. change slice creation (avoid additional view construction)
2. fix bug with view sizes
3. introduce custom data container in storage (for future customization with shared memory allocation)
4. negate operator
5. assignment to constant scalar
6. some const-correctness
7. additional tests

Tensors refactoring

---

utilities/include/alps/numeric/tensors.hpp

Tensor common

---

accumulators/test/mean_err_count.cpp
params/include/alps/params/params_impl.hpp
params/src/iniparser_interface.cpp
params/src/params.cpp
params/test/params.cpp
params/test/params_cmdline.cpp
params/test/params_formats.cpp
params/test/params_origins.cpp
utilities/include/alps/numeric/boost_array_functions.hpp
utilities/include/alps/numeric/rectangularize.hpp
utilities/include/alps/numeric/vector_functions.hpp
utilities/include/alps/utilities/mpi_map.hpp
utilities/include/alps/utilities/mpi_pair.hpp
utilities/include/alps/utilities/mpi_vector.hpp
utilities/src/gtest_par_xml_output.cpp
utilities/test/test_utils.hpp

It's an "accidental" branch due to a conflict.
Should be merged once checks passed --- or maybe even right away.

Merging tostring_insteadof_lexicalcast branch

---

.zenodo.json

Updated author's list for Zenodo

---

accumulators/src/mpi.cpp
accumulators/test/accumulator_generator.hpp
accumulators/test/mean_err_count.cpp
gf/include/alps/gf/mesh.hpp
gf/include/alps/gf/piecewise_polynomial.hpp
gf/test/mpi_guard.cpp
hdf5/test/hdf5_io_types.cpp
params/include/alps/params/params_impl.hpp
params/include/alps/params/serialize_variant.hpp
params/src/iniparser_interface.cpp
params/src/params.cpp
params/test/old/param_ostream.cpp
params/test/old/repeated_options.cpp
params/test/params.cpp
params/test/params_cmdline.cpp
params/test/params_formats.cpp
params/test/params_origins.cpp
tutorials/mc/ising2_mc/main_mpi.cpp
utilities/include/alps/numeric/boost_array_functions.hpp
utilities/include/alps/numeric/rectangularize.hpp
utilities/include/alps/numeric/vector_functions.hpp
utilities/include/alps/type_traits/slice.hpp
utilities/include/alps/utilities/mpi_map.hpp
utilities/include/alps/utilities/mpi_pair.hpp
utilities/include/alps/utilities/mpi_vector.hpp
utilities/src/gtest_par_xml_output.cpp
utilities/test/test_utils.hpp

This merge seems to produce no changes (the respective changes have been already committed), but let's do it anyway to tie loose ends.

to_string instead of lexical_cast

---

accumulators/include/alps/accumulators/namedaccumulators.hpp
accumulators/src/namedaccumulators.cpp
accumulators/test/CMakeLists.txt
accumulators/test/assign_acc.cpp

This should close #548.
Igor (@krivenko), if you have time, could you also have a brief look, please?

Fixed infinite recursion in named accumulators assignment

---

params/include/alps/params.hpp
params/include/alps/params/params_impl.hpp
params/src/params.cpp
params/test/CMakeLists.txt
params/test/params_hdf5.cpp
params/test/params_hdf5_with_ini.cpp

Override params restored from HDF5 via cmdline

---

common/cmake/ALPSEnableEigen.cmake

Fix Eigen3 co-installation when requested as the 2nd attempt

---

utilities/include/alps/numeric/is_zero.hpp
utilities/test/CMakeLists.txt
utilities/test/is_zero.cpp

Fixed is_zero for float
Add unit test

Fix is_zero.hpp (resubmitted against the master branch)

---

utilities/include/alps/numeric/tensors/tensor_base.hpp
utilities/test/tensor_test.cpp

Fix compilation failure with clang-3.4.2 (#576)

---

alea/test/CMakeLists.txt
alea/test/compare.cpp

[alea] Add test for operator== and operator!=

---

params/src/params.cpp
params/test/params_bcast_mpi.cpp

Fix parallel alps::params ctor

---

gf/include/alps/gf/mesh/chebyshev_mesh.hpp

(I want to try Inception pull request.)

Make NDEBUG guard for uninitialized Chebyshev mesh

---

params/test/dictionary.cpp
params/test/dictionary_hdf5.cpp
params/test/params_formats.cpp
params/test/params_hdf5.cpp

Fix tests for 32-bit OS, where sizeof(int) == sizeof(long)

[params] Fix tests for 32-bit OS

---

gf/include/alps/gf/fourier.hpp
gf/test/fourier_test.cpp

Cleaning up the `fourier.hpp` mess.
I suppose we need to use fft at some point.
Also we need to have tau->omega transform. 
Without this it's sort of pointless.

[gf] Overhaul of Fourier transforms

---

gf/include/alps/gf/fourier.hpp
tutorials/gf/gf.cpp

1. I/O operations
2. Arithmetic operations

[gf] More on GF tutorials

---

alea/include/alps/alea/internal/pooling.hpp
alea/include/alps/alea/testing.hpp
alea/include/alps/alea/util/model.hpp
alea/src/model.cpp
alea/src/testing.cpp
alea/test/model.cpp

updated copyright notice

---

gf/include/alps/gf/piecewise_polynomial.hpp
utilities/include/alps/numeric/tensors/tensor_base.hpp
utilities/include/alps/numeric/vector_functions.hpp
utilities/include/alps/utilities/cast.hpp

No boost bind

---

common/cmake/ALPSEnableEigen.cmake

Update the Eigen3 download location

Updated Eigen3 download location
